version: "3"
services:
  # app:
  #   build: ./app
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - "api-gateway"

  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - user-service
  #     # - items-service
  #   # volumes:
  #   #   - ./api-gateway:/api

  # user-service:
  #   build: ./user-service
  #   ports:
  #     - "4040:4040"
    # volumes:
    #   - ./user-service:/user-service

  user-db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/user-db/storage:/var/lib/mysql:rw
      - ./db/user-db:/docker-entrypoint-initdb.d/:ro

  items-db:
    image: mysql:5.7
    ports:
      - "42000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/items-db/storage:/var/lib/mysql:rw
      - ./db/items-db:/docker-entrypoint-initdb.d/:ro